tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "playcover/playcover"
tap "powershell/tap"
brew "act"
brew "automake"
brew "bazelisk"
brew "openssl@3"
brew "chezmoi"
brew "clang-format"
brew "cmake"
brew "coreutils"
brew "git"
brew "gnu-tar"
brew "gnupg"
brew "gperf"
brew "openjdk"
brew "gradle"
brew "hopenpgp-tools"
brew "jadx"
brew "jenv"
brew "kdoctor"
brew "kotlin"
brew "latexindent"
brew "llvm"
brew "mas"
brew "nvm"
brew "opencc"
brew "opentofu"
brew "p7zip"
brew "pinentry-mac"
brew "pkgconf"
brew "repo"
brew "ruby"
brew "rustup"
brew "tldr"
brew "wget"
brew "ykman"
brew "ykpers"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "powershell/tap/powershell"
cask "anydesk"
cask "bartender"
cask "betterzip"
cask "beyond-compare"
cask "calibre"
cask "chatgpt"
cask "chrome-remote-desktop-host"
cask "clashx"
cask "discord"
cask "docker"
cask "dotnet-sdk"
cask "firefox"
cask "git-credential-manager"
cask "gitkraken"
cask "google-drive"
cask "gpg-suite"
cask "hiddenbar"
cask "jetbrains-toolbox"
cask "macfuse"
cask "nomachine"
cask "obs"
cask "parallels"
cask "playcover-community"
cask "prusaslicer"
cask "snipaste"
cask "squirrel"
cask "tailscale"
cask "telegram-desktop"
cask "temurin@11"
cask "temurin@17"
cask "temurin@21"
cask "visual-studio-code"
cask "wireshark"
cask "zerotier-one"
mas "Bitwarden", id: 1352778147
mas "Developer", id: 640199958
mas "Keynote", id: 409183694
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Windows App", id: 1295203466
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
