#!/bin/bash

function check-brew {
  if ! [ -x "$(command -v brew)" ]; then
    if ! [ -x "$(command -v /opt/homebrew/bin/brew)" ]; then
      echo "Installing brew..."
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
}

function configure-gpg {
  sudo rm /usr/local/MacGPG2/bin/gpg 2>/dev/null
  sudo rm /usr/local/MacGPG2/bin/gpg-agent 2>/dev/null
  sudo rm /usr/local/bin/gpg 2>/dev/null
}

function setup-chezmoi {
  if ! [ -x "$(command -v chezmoi)" ]; then
    echo "Installing chezmoi..."
    brew install chezmoi
  fi
  chezmoi init Omico --depth 1 --force
}

function configure-oh-my-zsh {
  if ! [ -d "$ZSH" ]; then
    echo "Installing oh-my-zsh..."
    RUNZSH=no sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  fi
  if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  fi
  if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  fi
  brew install thefuck
  brew install --cask font-fira-mono-nerd-font
}

function clone-rime-auto-deploy {
  if ! [ -d "$HOME/Git/Mark24Code/rime-auto-deploy" ]; then
    echo "Cloning rime-auto-deploy..."
    git clone --depth=1 https://github.com/Mark24Code/rime-auto-deploy.git --branch latest "$HOME/Git/Mark24Code/rime-auto-deploy"
  fi
}

check-brew
configure-gpg
brew install git
brew install --cask visual-studio-code
setup-chezmoi
configure-oh-my-zsh
chezmoi apply
clone-rime-auto-deploy
