#!/bin/bash

function check-brew {
  if ! [ -x "$(command -v brew)" ]; then
    if ! [ -x "$(command -v /opt/homebrew/bin/brew)" ]; then
      echo "Installing brew..."
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
}

function setup-chezmoi {
  if ! [ -x "$(command -v chezmoi)" ]; then
    echo "Installing chezmoi..."
    brew install chezmoi
  fi
  chezmoi init Omico --depth 1 --force
}

function clone-rime-auto-deploy {
  if ! [ -d "$HOME/Git/Mark24Code/rime-auto-deploy" ]; then
    echo "Cloning rime-auto-deploy..."
    git clone --depth=1 https://github.com/Mark24Code/rime-auto-deploy.git --branch latest "$HOME/Git/Mark24Code/rime-auto-deploy"
  fi
  cp -f "$HOME"/.local/share/chezmoi/rime/*.custom.yaml "$HOME/Git/Mark24Code/rime-auto-deploy/custom"
}

check-brew
brew install git
brew install --cask visual-studio-code
brew install --cask font-fira-mono-nerd-font
setup-chezmoi
chezmoi apply
clone-rime-auto-deploy
