#!/bin/bash

function update-git-repo() {
  REPO_DIRECTORY="$1"
  git -C "$REPO_DIRECTORY" fetch --all
  git -C "$REPO_DIRECTORY" reset --hard
}

chezmoi update

brewup restore
brewup update

update-git-repo "$HOME/Library/Rime"
cp -f "$HOME"/.local/share/chezmoi/rime/*.custom.yaml "$HOME/Library/Rime"
